FROM drupaldocker/php-dev:7.2-cli-2.x

# Default user uid for ubuntu users
ARG UID=1000
ARG GID=1000

# Default username of newly created user and group in within the container.
ARG NAME=drupal

RUN addgroup -g ${GID} ${NAME} \
 && adduser -D -u ${UID} -G ${NAME} ${NAME} \
 && adduser ${NAME} www-data

RUN mkdir -p /var/www/html/drupal-files && chown www-data:www-data /var/www/html/drupal-files && chmod g+ws /var/www/html/drupal-files
RUN mkdir -p /var/www/html/web/sites/default/files && chown www-data:www-data /var/www/html/web/sites/default/files && chmod g+ws /var/www/html/web/sites/default/files
RUN mkdir -p /var/www/html/web/sites/simpletest && chown www-data:www-data /var/www/html/web/sites/simpletest && chmod g+ws /var/www/html/web/sites/simpletest

RUN apk add --no-cache \
   fish \
   less \
   bash \
   bc \
   groff \
   util-linux \
   coreutils \
   man \
   mdocml-apropos \
   python \
   nodejs \
   patch \
 && sed -i -e "s/bin\/ash/usr\/bin\/fish/" /etc/passwd

RUN curl -Lo /etc/fish/functions/fisher.fish --create-dirs https://git.io/fisher \
 && chmod -R a+x /etc/fish/functions

RUN cd /root \
 && wget https://raw.github.com/nvie/gitflow/develop/contrib/gitflow-installer.sh \
 && chmod +x gitflow-installer.sh \
 && ls -lah \
 && ./gitflow-installer.sh

ENV SHELL /usr/bin/fish

RUN echo "%www-data ALL=(ALL) NOPASSWD:ALL" > /etc/sudoers.d/50-local

USER ${NAME}

RUN /usr/bin/fish -c "fisher add \
    fisherman/z \
    fisherman/metro \
    fisherman/host_info \
    fisherman/pwd_info \
    fisherman/segment \
    fisherman/humanize_duration \
    fisherman/last_job_id \
    fisherman/pwd_is_home \
    fisherman/git_util \
    fisherman/done"

CMD /usr/bin/fish

